; Graph-native source: lists fold left into pairs before linking.
; A new leftmost symbol names its form. Later new symbols become atoms.

((I x x)
 (K x y x)
 (S x y z ((x z) (y z)))
 (B f g x (f (g x)))
 (C f x y ((f y) x))
 (W f x ((f x) x))
 (M x (x x))
 (Y f (f (Y f)))

 (True x y x)
 (False x y y)
 (If p x y (p x y))
 (Not p (p False True))
 (And p q (p q False))
 (Or p q (p True q))
 (Pair x y f (f x y))
 (First p (p K))
 (Second p (p False))
 (App p q (p q))

 (Zero f x x)
 (Succ n f x (f (n f x)))

 ; (I a)
 ; (K a b)
 (S a b c)
 ; (B f g x)
 ; (C f x y)
 ; (W f x)
 ; (M x)
 ; (True a b)
 ; (False a b)
 ; (If p a b)
 ; (Not True)
 ; (And True False)
 ; (Or False True)
 ; (Pair a b f)
 ; (First (Pair a b))
 ; (Second (Pair a b))
 ; (Y I) ; repeats forever
 ; (Y (K a))
 ; (Zero I a)
 ; (Succ Zero I a)
 )
