export default
[{ languageOptions: { ecmaVersion: 'latest',
                      sourceType: 'module',
                      globals: { console: 'readonly',
                                 URL: 'readonly',
                                 Event: 'readonly',
                                 PopStateEvent: 'readonly',
                                 document: 'readonly',
                                 window: 'readonly',
                                 process: 'readonly',
                                 fetch: 'readonly' }},
   rules: {
     'array-bracket-newline': ['warn', 'consistent'],
     'array-bracket-spacing': ['warn', 'never'],
     'arrow-parens': ['warn', 'as-needed'],
     'arrow-spacing': 'warn',
     'comma-dangle': ['warn', 'never'],
     'comma-spacing': ['warn', { before: false, after: true }],
     'comma-style': ['warn', 'last'],
     'computed-property-spacing': ['warn', 'never'],
     'eol-last': ['warn', 'always'],
     indent: ['warn', 2,
              { ArrayExpression: 'first',
                CallExpression: { arguments: 'first' },
                flatTernaryExpressions: false,
                FunctionDeclaration: { parameters: 'first' },
                FunctionExpression: { parameters: 'first' },
                ignoreComments: false,
                ignoredNodes: [
                  // 'MemberExpression',
                  // 'ObjectExpression > .punctuation:last-child'
                ],
                ImportDeclaration: 'first',
                MemberExpression: 1,
                ObjectExpression: 'first',
                offsetTernaryExpressions: true,
                outerIIFEBody: 1,
                StaticBlock: { body: 1 },
                SwitchCase: 1,
                VariableDeclarator: 'first' }],
     'key-spacing': ['warn', { mode: 'minimum' }],
     'linebreak-style': ['error', 'unix'],
     'max-len': ['warn',
                 { code: 80,
                   ignoreUrls: true,
                   ignoreRegExpLiterals: true,
                   ignoreStrings: true,
                   ignoreTemplateLiterals: true }],
     'no-extra-parens': ['warn', 'all',
                         { allowParensAfterCommentPattern: '@type' }],
     'no-multiple-empty-lines': ['warn', { max: 2, maxEOF: 1 }],
     'no-multi-spaces': ['warn', { ignoreEOLComments: true,
                                   exceptions: { Property: false }}],
     'no-trailing-spaces': 'warn',
     'no-undef': 'warn',
     'no-unused-vars': ['warn', { args: 'all',
                                  varsIgnorePattern: '^_',
                                  argsIgnorePattern: '^_' }],

     'object-curly-newline': ['warn', { consistent: true }],
     'object-curly-spacing': ['warn',
                              'always',
                              { arraysInObjects: false,
                                objectsInObjects: false }],
     'operator-linebreak': ['warn',
                            'before',
                            { overrides: { '=': 'ignore' }}],
     'prefer-rest-params': 'warn',
     'quote-props': ['warn', 'as-needed'],
     quotes: ['warn', 'single'],
     semi: ['warn', 'never'],
     'sort-imports': ['warn', { ignoreDeclarationSort: true }],
     'space-before-function-paren': ['warn', { anonymous: 'never',
                                               asyncArrow: 'always',
                                               named: 'never' }],
     'spaced-comment': ['warn', 'always'],
     'space-in-parens': ['warn', 'never'],
     'space-infix-ops': 'warn'
   }}]

