export default
{ title: 'pfernandez.github.io',
  pages: [{ path: 'ski-mathml-x3dom',
            summary: 'SKI MathML + X3DOM',
            items: [{ label: 'Demo',
                      file: 'demo.js',
                      keepAlive: true,
                      default: true }]},
          { path: 'collapse',
            summary: 'Collapse',
            items: [{ label: 'Interpreter',
                      file: 'interpreter.js',
                      keepAlive: true }]},
          { path: 'basis',
            summary: 'Basis',
            items: [{ label: 'Visualizer',
                      file: 'visualizer.js',
                      keepAlive: true },
                    { label: 'Overview',
                      file: 'overview.md' }]},
          { path: 'nonplanar-polygons',
            summary: 'Nonplanar Polygons',
            items: [{ label: 'Visualization',
                      file: 'visualization.js',
                      keepAlive: true },
                    { label: 'Description',
                      file: 'description.md' }]}]}
