export default
{ title: 'pfernandez.github.io',
  pages: [{ path: 'graph-reduction',
            summary: 'Graph Reduction',
            items: [{ label: 'SKI',
                      file: 'ski.js',
                      default: true },
                    { label: '2D Collapse',
                      file: 'collapse-2d.js' }]},
          { path: 'nonplanar-polygons',
            summary: 'Nonplanar Polygons',
            items: [{ label: 'Visualization',
                      file: 'visualization.js' },
                    { label: 'Description',
                      file: 'description.md' }]}],
  keepAlive: true }
